server:
  port: 5050

spring:
  main:
    allow-circular-references: true # 使用自动循环引解决statBiz依赖于ProductOrderService形成的循环依赖关系
  application:
    name: reuse_market
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://*:3306/reuse_market?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: reuse_market # 本地环境为root
    password: ~~~~~~
  redis:
    host: ~~~~~~
    # 数据库索引
    database: 2
    # 端口
    port: 6379
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: 100
    password: '123456'
  rabbitmq:
    host: ~~~~~~
    port: 5672
    username: ~~~~~~
    password: ~~~~~~
    connection-timeout: 2s
    virtual-host: /admin
    template:
      retry:
        enabled: true
        multiplier: 2
    publisher-confirm-type: correlated # 消息异步确认模式
    publisher-returns: true
    listener: #消费者确认机制
      simple:
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 1
          max-attempts: 3
          stateless: false
        acknowledge-mode: auto # 自动确认模式
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
gitee:
  client-id: ~~~~~~
  client-secret: ~~~~~~
  redirect-uri: ~~~~~~
github:
  client-id: ~~~~~~
  client-secret: ~~~~~~
  redirect-uri: ~~~~~~
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
zhufan:
  # 项目配置
  app:
    logoPath: "/root/LOGO.png"
    shareUrl: ~~~~~~
  alioss:
    endpoint: ~~~~~~
    access-key-id: ~~~~~~
    access-key-secret: ~~~~~~
    bucket-name: ~~~~~~
#文件上传管理X-File-Storage
dromara:
  x-file-storage: #文件存储配置
    default-platform: qiniu-kodo-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    qiniu-kodo:
      - platform: qiniu-kodo-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ~~~~~~
        secret-key: ~~~~~~
        bucket-name: cookmarket
        domain: ~~~~~~ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: reuse-market-images/ # 基础路径
alipay:
  appId: ~~~~~~
  appPrivateKey: ~~~~~~
# job:
#   accessToken: ywb123456
#   admin:
#     addresses: http://localhost:8085/xxl-job-admin
#   executor:
#     appname: reuse-market
#     address:
#     ip:
#     port: 9999
#     logpath: /data/applogs/xxl-job/jobhandler
#     logretentiondays: 30
